coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

flag_management:
  default_rules:
    carryforward: true

comment:
  layout: 'reach, diff, flags, files'
  require_changes: false
